var = input('Digite algo:')
print('O tipo primitivo desse valor é', type(var))
print('É numérico?', var.isnumeric())
print('É alfabético?', var.isalpha())
print('É alfanumérico?', var.isalnum())
print('É decimal?', var.isdecimal())
print('É maior?', var.isupper())
print('É menor?', var.islower())
print('Só tem espaços?',var.isspace())